### PR TITLE
Correct tree depth computation

### LINKED ISSUE #77: Calculation of tree depth seems wrong
For example, on the documentation [page](https://integralequations.github.io/HMatrices.jl/dev/#:~:text=per%20leaf%3A%202777222-,depth%20of%20tree%3A%200,-compression%20ratio%3A%2021.819426), the number on the "depth of tree" seems wrong.
> HMatrix of Float64 with range 1:10000 × 1:10000
	 number of nodes in tree: 3353
	 number of leaves: 2515 (800 admissible + 1715 full)
	 min rank of sparse blocks : 5
	 max rank of sparse blocks : 8
	 min length of dense blocks : 625
	 max length of dense blocks : 4300
	 min number of elements per leaf: 625
	 max number of elements per leaf: 2777222
	 **depth of tree: 0**
	 compression ratio: 21.819426

### PR DESCRIPTION
**Pull request by chaozg**
fixed #77 

Hi @maltezfaria, I was (again) reading your documentation and found the existing computation of the tree depth seems incorrect, so I came up with this tiny PR. Specifically,
- I added a `isrootnode(H)` to avoid clash with `isroot(H)`
- In `_show`, I changed the computation of depth from `leaves_` to `nodes_`. Does it make more sense to count the depth based on the nested nodes, instead of the final leaves? I might be very wrong here. Anyhow I sent this PR for your review.

With the PR, the following code will somehow show the tree structure of the deepest tree/node. The opacity and number show the level of the corresponding node, while the rectangular shows where the node is.
```julia
using HMatrices, LinearAlgebra, StaticArrays, Plots
using Random

Random.seed!(1234)

const Point3D = SVector{3,Float64}
# sample some points on a sphere
m = 500 #500
X = Y = [Point3D(sin(θ)cos(ϕ),sin(θ)*sin(ϕ),cos(θ)) for (θ,ϕ) in zip(π*rand(m),2π*rand(m))]
function G(x,y) 
  d = norm(x-y) + 1e-8
  1/(4π*d)
end
K = KernelMatrix(G,X,Y)

H = assemble_hmatrix(K;atol=1e-6)

show(H)

# %% get the deepest node
nodes = HMatrices.nodes(H)
depths = map(HMatrices.depth, nodes)
println("max depth: ", maximum(depths))
deepest_node_index = argmax(depths)

deepest_node = nodes[deepest_node_index]

# %% plot the deepest node and all its ancestors
rectangle(w, h, x, y) = Shape(x .+ [0,w,w,0], y .+ [0,0,h,h])
function plot_node_ancestors(node, p=Nothing)
    if p == Nothing
        p = plot(aspect_ratio=:equal)
    end
    level = 1
    while !HMatrices.isrootnode(node) # plot until the root node
        plot!(rectangle(node.rowtree.index_range[end]-node.rowtree.index_range[1],
                    node.coltree.index_range[end]-node.coltree.index_range[1],
                    node.rowtree.index_range[1],
                    node.coltree.index_range[1]), opacity=.5, color=:green, width=1)
        plot!([node.rowtree.index_range[1], node.rowtree.index_range[end]],[node.coltree.index_range[end], node.coltree.index_range[1]],width=1, color=:black)
        annotate!(((node.rowtree.index_range[end]+node.rowtree.index_range[1])*0.5, (node.coltree.index_range[end]+node.coltree.index_range[1])*0.5, text(level, 10, :black)))
        node = HMatrices.parentnode(node)
        level += 1
    end
    return p
end

p = plot(H)
p = plot_node_ancestors(deepest_node, p)
display(p)
```

plot_51

### CODE REVIEW

**Comment by maltezfaria** [comment]
This looks good, and it is (almost) along the lines of what I had in mind. I think the issue comes from my misuse of `parent` instead of `parentnode`.

File: src/hmatrix.jl [hunk 1]
```diff
@@ -69,6 +69,7 @@ const HTriangular = Union{HLowerTriangular,HUpperTriangular}
 # parentnode. Ducktype and hope for the best.
 hasdata(H) = !isnothing(data(parent(H)))
 isroot(H) = parent(H) === H
+isrootnode(H) = H.parentnode === H
```
Comment (maltezfaria) [inline src/hmatrix.jl:72]: Don't think this is needed. Instead `isroot` should call `parentnode` instead of a `parent`

File: src/hmatrix.jl [hunk 2]
```diff
@@ -155,8 +156,8 @@ function _show(io, hmat, allow_empty = false)
     points_per_leaf = map(length, leaves_)
     @printf(io, "\n\t min number of elements per leaf: %i", minimum(points_per_leaf))
     @printf(io, "\n\t max number of elements per leaf: %i", maximum(points_per_leaf))
-    depth_per_leaf = map(depth, leaves_)
-    @printf(io, "\n\t depth of tree: %i", maximum(depth_per_leaf))
+    depth_per_node = map(depth, nodes_)
+    @printf(io, "\n\t depth of tree: %i", maximum(depth_per_node))
```
Comment (maltezfaria) [inline src/hmatrix.jl:160]: Why not look only at the leaves for the depth? I missed the point here.

File: src/utils.jl [hunk 3]
```diff
@@ -82,10 +82,10 @@ Overload this function if your structure has a more efficient way to compute
 `depth` (e.g. if it stores it in a field).
 """
 function depth(tree, acc = 0)
-    if isroot(tree)
+    if isrootnode(tree)
```
Comment (maltezfaria) [inline src/utils.jl:85]: Again, I think the faulty logic is in `isroot`, so fixing that would make this change unnecessary

File: src/utils.jl [hunk 4]
```diff
@@ -82,10 +82,10 @@ Overload this function if your structure has a more efficient way to compute
...
         return acc
     else
-        depth(parent(tree), acc + 1)
+        depth(parentnode(tree), acc + 1)
```
Comment (maltezfaria) [inline src/utils.jl:88]: Nice catch!

**Review by maltezfaria — COMMENTED** [review]
Left a few minor comments.

File: src/hmatrix.jl (hunk 2 above)
Comment (chaozg) [reply src/hmatrix.jl]: I just updated to leaves. My brain was not with me : )

File: src/hmatrix.jl (hunk 1 above)
Comment (chaozg) [reply src/hmatrix.jl:72]: The reason I added `isrootnode` is because I found that `HMatrices.isroot` always return True for any leave. See
```julia
using Pkg
Pkg.activate(".")

using HMatrices, LinearAlgebra, StaticArrays, Plots
using Random

Random.seed!(1234)

const Point3D = SVector{3,Float64}
# sample some points on a sphere
m = 1000 #500
X = Y = [Point3D(sin(θ)cos(ϕ),sin(θ)*sin(ϕ),cos(θ)) for (θ,ϕ) in zip(π*rand(m),2π*rand(m))]
function G(x,y) 
  d = norm(x-y) + 1e-8
  1/(4π*d)
end
K = KernelMatrix(G,X,Y)

H = assemble_hmatrix(K;atol=1e-6)

show(H)

# %% get the deepest node
leaves = HMatrices.leaves(H)

for i=1:10
    println(HMatrices.isroot(leaves[2])) # ruturns always true
end
```

Comment (maltezfaria) [reply src/hmatrix.jl:72]: But isn't that because `isroot` was wrong before? If you change `isroot` to use `parentnode`, I think it all works and there is not need for `isrootnode`. The issue came from the fact that `parent` has a certain meaning for an `AbstractMatrix`, and I misused it in some places (e.g. `parent` of a lazy adjoint points to the original matrix).

Comment (chaozg) [reply src/hmatrix.jl]: I guess you're suggesting this [version](https://github.com/IntegralEquations/HMatrices.jl/pull/78/commits/7b0f6d24ba2a17f0270a3e7473e5b7f98dc243b2), right? Unfortunately, this version won't pass the`triangular_test`, particularly in this section on computing `approx`. I have to admit that I failed to find the reason why as debugging becomes very slow (I'm still new to Julia and don't know how to do proper debugging yet)
```julia
    ## 3.3
    compressor = PartialACA(; atol = 1e-8)
    exact = ldiv!(UnitLowerTriangular(H_full), copy(H_full))
    approx = ldiv!(UnitLowerTriangular(H), deepcopy(H), compressor)
    @test exact ≈ Matrix(approx; global_index = false)
```

Comment (maltezfaria) [reply src/hmatrix.jl]: Thanks for spotting this: another bug that surfaced when you fixed the first bug. 

The issue is that line 27 in `multiplication.jl` with `@assert isroot(C) || !hasdata(parent(C))` should be removed (I thought about this and I don't think it makes sense to require that). 

If you do that I think we can merge this PR 🎉

Comment (chaozg) [reply src/hmatrix.jl]: Great! Just did as suggested

File: src/utils.jl (hunk 3 above)
Comment (chaozg) [reply src/utils.jl]: Agreed

**Review by maltezfaria — APPROVED** [review]
